host: host
port: 80
account: account
channel_name: channel_name
channel_password: channel_password
sleep_seconds: 10
tls: false

# How much time to wait between fetches from the QST server
sleep_seconds: 10

# Percent of respondents that never reply
no_reply_percent: 0.2

# Percent of respondents that have a delay in their reply
delay_reply_percent: 0.2
# Of the above, minimum time in seconds of that delay (min..max)
delay_reply_min_seconds: 0
# Of the above, maximum time in seconds of that delay (min..max)
delay_reply_max_seconds: 60

# Percent of respondents that reply an incorrect answer
incorrect_reply_percent: 0.2

# If true, once a respondent replies, it will always reply
sticky_respondents: true

# How many incoming messages to fetch at once
incoming_batch_size: 100
